### ISSUE TITLE
PyPI / pip installation

### ISSUE THREAD

**Issue by DrShushen** [picnixz/sphinx-zeta-suppress#3]
I find this extension very useful, but it seems there isn't a PyPI (pip) installation at the moment? Would be great to have that for ease of use.

**Comment by picnixz** [comment]
Oh yes. Actually I never released things on PyPI so I don't really know how to do it. Unfortunately, I don't have much time until next year due to my PhD thesis so I won't be able to make a release for that soon.

I will try to find some time for that but I cannot guarantee anything :(

**Comment by DrShushen** [comment]
Haha, I am also doing a PhD. I think I will be able to help you with this, as I have released projects on PyPI before. Are you happy for me to submit a PR with the changes at some point soon?

**Comment by picnixz** [comment]
I would be happy but I don't know whether I'll have time to look at it!

**Comment by flying-sheep** [comment]
It’s pretty easy actually.

Step 0: create a pypi account, set up 2FA, …

Then:

1. create an GitHub environment for this project called `pypi` or `release` or so
2. create `.github/workflows/publish.yml` or `…/release.yml` or so:

	```yaml
	jobs:
	  pypi-publish:
	    name: Upload release to PyPI
	    runs-on: ubuntu-latest
	    environment:
	      name: pypi
	      url: https://pypi.org/p/sphinx-zeta-suppress
	    permissions:
	      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
	    steps:
	    - uses: actions/checkout@v4
	    - uses: actions/setup-python@v4
	      with:
	        python-version: "3.x"
            cache: pip
	    - run: pip install build
	    - run: python -m build
	    - name: Publish package distributions to PyPI
	      uses: pypa/gh-action-pypi-publish@release/v1
	```

3. [fill out a single form](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/) with the file name and env name you chose
4. create a release using the GitHub UI

repeat step 1-4 for each project, and step 5 for each release
